#!/usr/bin/env bash
# Ninja OS3_A16 runtime pack orchestrator. Does not read .mtcr at runtime.
set -euo pipefail
NINJA_PACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; export NINJA_PACK_DIR
REPO_ROOT="$(cd "$NINJA_PACK_DIR/../../../../../" && pwd)"; export NINJA_REPORT_DIR="${NINJA_REPORT_DIR:-$REPO_ROOT/out/reports/ninja-os3-a16}"
export DZ_BASE_STYLE_ID="${DZ_BASE_STYLE_ID:-ninja}"
MODE="${DZ_STYLE_EXECUTION_MODE:-final}"
ninja_gate() { local platform="${DZ_PLATFORM_ID:-${PLATFORM_ID:-${PLATFORM:-}}}" android="${ANDROID_VERSION:-${ROM_ANDROID_VERSION:-}}" sdk="${SDK_VERSION:-${ANDROID_SDK:-}}" FINAL_STYLE="${DZ_FINAL_STYLE_ID:-${DZ_REQUESTED_STYLE:-${DZ_STYLE_ID:-}}}"; FINAL_STYLE="$(echo "$FINAL_STYLE" | tr '[:upper:]' '[:lower:]')"; [[ "$FINAL_STYLE" == "ninja" ]] || { echo "[Ninja][OS3_A16] SKIPPED: final style is not ninja (${FINAL_STYLE:-unknown})"; exit 0; }; [[ "$MODE" == "base" ]] && { echo "[Ninja][OS3_A16] SKIPPED: Ninja manual pack cannot run in base mode"; exit 0; }; [[ "$platform" == "OS3_A16" ]] || { echo "[Ninja][OS3_A16] SKIPPED: platform is not OS3_A16 (${platform:-unknown})"; exit 0; }; [[ "$android" == "16" || "$sdk" == "36" ]] || { echo "[Ninja][OS3_A16] SKIPPED: not Android 16 / SDK 36"; exit 0; }; }
find_rom_root() { local candidates=("${1:-}" "${ROM_ROOT:-}" "${DZ_ROM_ROOT:-}" "${EXTRACTED_ROM_ROOT:-}" "${EXTRACT_DIR:-}" "${WORK_DIR:-}" "$REPO_ROOT/work" "$REPO_ROOT/output" "$REPO_ROOT/out"); local c found; for c in "${candidates[@]}"; do [[ -n "$c" && -d "$c" ]] || continue; if [[ -f "$c/system/framework/framework.jar" || -f "$c/system_ext/priv-app/MiuiSystemUI/MiuiSystemUI.apk" ]]; then printf '%s\n' "$c"; return 0; fi; found=$(find "$c" -maxdepth 5 \( -path '*/system/framework/framework.jar' -o -path '*/system_ext/priv-app/MiuiSystemUI/MiuiSystemUI.apk' \) -print -quit 2>/dev/null || true); [[ -n "$found" ]] && { printf '%s\n' "${found%%/system/*}"; return 0; }; done; return 1; }
find_apktool_cmd() { command -v apktool >/dev/null 2>&1 && { echo apktool; return 0; }; local jar; jar=$(find "$REPO_ROOT" -iname 'apktool*.jar' -print -quit 2>/dev/null || true); [[ -n "$jar" ]] && echo "java -jar $jar" && return 0; return 1; }
find_baksmali_cmd() { command -v baksmali >/dev/null 2>&1 && { echo baksmali; return 0; }; local jar; jar=$(find "$REPO_ROOT" -iname 'baksmali*.jar' -print -quit 2>/dev/null || true); [[ -n "$jar" ]] && echo "java -jar $jar" && return 0; return 1; }
find_smali_cmd() { command -v smali >/dev/null 2>&1 && { echo smali; return 0; }; local jar; jar=$(find "$REPO_ROOT" -iname 'smali*.jar' -print -quit 2>/dev/null || true); [[ -n "$jar" ]] && echo "java -jar $jar" && return 0; return 1; }
apply_to_decoded_dir() { local module="$1" decoded="$2" target_label="$3"; [[ -d "$decoded" ]] || { echo "[Ninja][OS3_A16] SKIPPED: decoded dir missing for $target_label"; return 0; }; local roots=(); while IFS= read -r d; do roots+=("$d"); done < <(find "$decoded" -maxdepth 1 -type d -name 'smali*' | sort); export SMALI_DIRS="$(IFS=:; echo "${roots[*]}")"; export APK_DECOMPILED_DIR="$decoded"; source "$NINJA_PACK_DIR/patches/ninja_smali_master.sh"; echo "[Ninja][OS3_A16][$target_label] Applying $module patches"; apply_all_ninja_smali_patches "$module"; }
patch_jar_module() { local module="$1" target="$2" decoded_env_var="$3" target_label="$4"; local decoded_override="${!decoded_env_var:-}"; if [[ -n "$decoded_override" ]]; then apply_to_decoded_dir "$module" "$decoded_override" "$target_label"; return $?; fi; [[ -f "$target" ]] || { echo "[Ninja][OS3_A16] SKIPPED: $module target missing $target"; return 0; }; local baksmali_cmd smali_cmd; baksmali_cmd=$(find_baksmali_cmd) || { echo "[Ninja][OS3_A16] ERROR: baksmali not found for $module"; return 1; }; smali_cmd=$(find_smali_cmd) || { echo "[Ninja][OS3_A16] ERROR: smali not found for $module"; return 1; }; local tmp="$NINJA_REPORT_DIR/work/$module"; rm -rf "$tmp"; mkdir -p "$tmp/dex" "$tmp/out"; cp -f "$target" "$target.ninja.bak"; (cd "$tmp/dex" && unzip -q "$target" 'classes*.dex'); local dex smalidir index=1 roots=(); for dex in "$tmp/dex"/classes*.dex; do [[ -f "$dex" ]] || continue; if [[ "$(basename "$dex")" == "classes.dex" ]]; then smalidir="$tmp/smali"; else smalidir="$tmp/smali_classes$index"; fi; mkdir -p "$smalidir"; $baksmali_cmd d "$dex" -o "$smalidir"; roots+=("$smalidir"); index=$((index+1)); done; export SMALI_DIRS="$(IFS=:; echo "${roots[*]}")"; export APK_DECOMPILED_DIR=""; source "$NINJA_PACK_DIR/patches/ninja_smali_master.sh"; echo "[Ninja][OS3_A16][$target_label] Applying $module patches"; apply_all_ninja_smali_patches "$module"; rm -f "$tmp/dex"/classes*.dex; local root outdex num=1; for root in "${roots[@]}"; do if [[ "$num" -eq 1 ]]; then outdex="$tmp/dex/classes.dex"; else outdex="$tmp/dex/classes$num.dex"; fi; $smali_cmd a "$root" -o "$outdex"; num=$((num+1)); done; cp -f "$target.ninja.bak" "$tmp/out/$(basename "$target")"; (cd "$tmp/dex" && zip -q -u "$tmp/out/$(basename "$target")" classes*.dex); cp -f "$tmp/out/$(basename "$target")" "$target"; remove_oat_artifacts "$target"; echo "[Ninja][OS3_A16] APPLIED module $module -> $target"; }
patch_apk_module() { local module="$1" target="$2" decoded_env_var="$3" target_label="$4"; local decoded_override="${!decoded_env_var:-}"; if [[ -n "$decoded_override" ]]; then apply_to_decoded_dir "$module" "$decoded_override" "$target_label"; return $?; fi; [[ -f "$target" ]] || { echo "[Ninja][OS3_A16] SKIPPED: $module target missing $target"; return 0; }; local apktool_cmd; apktool_cmd=$(find_apktool_cmd) || { echo "[Ninja][OS3_A16] ERROR apktool not found"; return 1; }; local tmp="$NINJA_REPORT_DIR/work/$module"; rm -rf "$tmp"; mkdir -p "$tmp"; cp -f "$target" "$target.ninja.bak"; $apktool_cmd d -f "$target" -o "$tmp/apk"; local roots=(); while IFS= read -r d; do roots+=("$d"); done < <(find "$tmp/apk" -maxdepth 1 -type d -name 'smali*' | sort); export SMALI_DIRS="$(IFS=:; echo "${roots[*]}")"; export APK_DECOMPILED_DIR="$tmp/apk"; source "$NINJA_PACK_DIR/patches/ninja_smali_master.sh"; echo "[Ninja][OS3_A16][$target_label] Applying $module patches"; apply_all_ninja_smali_patches "$module"; $apktool_cmd b "$tmp/apk" -o "$tmp/patched.apk"; [[ -s "$tmp/patched.apk" ]] || { echo "[Ninja][OS3_A16] ERROR: rebuilt apk is empty for $module"; return 1; }; cp -f "$tmp/patched.apk" "$target"; remove_oat_artifacts "$target"; echo "[Ninja][OS3_A16] APPLIED module $module -> $target"; }
main() { ninja_gate; local rom_root; rom_root=$(find_rom_root "${1:-}") || { echo "[Ninja][OS3_A16] ERROR: ROM root not found"; exit 1; }; mkdir -p "$NINJA_REPORT_DIR"; echo "[Ninja][OS3_A16] Applying Ninja OS3_A16 Manual Runtime Smali Pack"; echo "[Ninja][OS3_A16] ROM root: $rom_root"; patch_jar_module framework "$rom_root/system/framework/framework.jar" "DZ_DECOMPILED_FRAMEWORK_DIR" "framework.jar"; patch_jar_module services "$rom_root/system/framework/services.jar" "DZ_DECOMPILED_SERVICES_DIR" "services.jar"; patch_jar_module miui_framework "$rom_root/system_ext/framework/miui-framework.jar" "DZ_DECOMPILED_MIUI_FRAMEWORK_DIR" "miui-framework.jar"; patch_jar_module miui_services "$rom_root/system_ext/framework/miui-services.jar" "DZ_DECOMPILED_MIUI_SERVICES_DIR" "miui-services.jar"; patch_apk_module systemui "$rom_root/system_ext/priv-app/MiuiSystemUI/MiuiSystemUI.apk" "DZ_DECOMPILED_SYSTEMUI_DIR" "MiuiSystemUI.apk"; patch_apk_module powerkeeper "$rom_root/system_ext/app/PowerKeeper/PowerKeeper.apk" "DZ_DECOMPILED_POWERKEEPER_DIR" "PowerKeeper.apk"; cat > "$NINJA_REPORT_DIR/active_mods_report.json" <<EOF
{"id":"ninja_os3_a16_pack","style":"ninja","platform":"OS3_A16","android":"16","status":"applied","report":"$NINJA_REPORT_DIR/ninja-os3-a16-summary.txt"}
EOF
echo "[Ninja][OS3_A16] complete"; }
main "$@"
